### ISSUE TITLE
发生闪退（安卓15）

### ISSUE THREAD

**Issue by akers4238** [maotoumao/MusicFree#367]
### ⠀

- [X] 已阅读 Q&A

### ⠀

- [X] 非插件导致（如搜索结果不全，无法导入等都属于插件问题）

### ⠀

- [X] 不与其他 issue 重复

### 问题描述

打开
播放
退出
重新打开-闪退+关闭播放

### 预期行为

略

### 详细的复现步骤

打开，播放，关闭，打开-闪退

### 截图

没有录上

### 日志

这个是本地抓取，不是应用的记录
java.lang.RuntimeException: Unable to start activity ComponentInfo{fun.upup.musicfree/fun.upup.musicfree.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4410)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4631)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6770)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6661)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:79)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:186)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:112)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:84)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2873)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9580)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
	at android.app.Activity.performCreate(Activity.java:9221)
	at android.app.Activity.performCreate(Activity.java:9177)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1538)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4392)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 30 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:65)
	at com.swmansion.rnscreens.ScreenStackFragment.<init>(ScreenStackFragment.kt:40)
	... 33 more

### 其他信息

小米14u 安卓15 os2

**Comment by maotoumao** [comment]
谢谢反馈，之前升级rn的时候改漏掉了，下个版本修复

**Comment by maotoumao** [comment]
新版本已修复
